IgniteUI/igniteui-blazor-examples

samples/grids/data-grid/column-pinning-picker/App.razor, samples/grids/data-grid/column-pinning-picker/Pages/DataGridColumnPinningPicker.razor, samples/grids/data-grid/column-pinning-picker/Services/DataGenerator.cs, samples/grids/data-grid/column-pinning-picker/Services/EmployeeData.cs
=> mdd-column-pinning-picker

samples/grids/data-grid/binding-local-data/App.razor, samples/grids/data-grid/binding-local-data/Pages/DataGridBindingLocalData.razor, samples/grids/data-grid/cell-activation/App.razor, samples/grids/data-grid/cell-activation/Pages/DataGridCellActivation.razor, samples/grids/data-grid/cell-activation/Services/DataGenerator.cs, samples/grids/data-grid/cell-activation/Services/EmployeeData.cs
Data-Grid BindingLocalData & CellActivation samples
=> mdd-binding-local-data-cell-activation

samples/grids/data-grid/column-pinning-toolbar/App.razor, samples/grids/data-grid/column-pinning-toolbar/Pages/DataGridColumnPinningToolbar.razor, samples/grids/data-grid/column-pinning-toolbar/Services/DataGenerator.cs, samples/grids/data-grid/column-pinning-toolbar/Services/EmployeeData.cs
=> mdd-column-pinning-toolbar

samples/grids/data-grid/row-pinning/App.razor, samples/grids/data-grid/row-pinning/Pages/DataGridRowPinning.razor, samples/grids/data-grid/row-pinning/Services/DataGenerator.cs, samples/grids/data-grid/row-pinning/Services/EmployeeData.cs
mdd-update-row-pinning-not-working
=> mdd-data-grid-row-pinning

samples/grids/data-grid/row-grouping/App.razor, samples/grids/data-grid/row-grouping/Pages/DataGridRowGrouping.razor, samples/grids/data-grid/row-grouping/Services/DataGenerator.cs, samples/grids/data-grid/row-grouping/Services/EmployeeData.cs
=> Mdd row grouping

samples/grids/data-grid/column-scrolling/App.razor, samples/grids/data-grid/column-scrolling/Pages/DataGridColumnScrolling.razor, samples/grids/data-grid/column-scrolling/Services/DataGenerator.cs, samples/grids/data-grid/column-scrolling/Services/EmployeeData.cs
mdd-data-grid-column-scrolling
=> mdd-data-grid-column-scrolling

samples/charts/financial-chart/indicator-customization/Pages/FinancialChartCustomIndicators.razor, samples/charts/financial-chart/indicator-customization/wwwroot/FinancialChartCustomIndicators.js, samples/charts/financial-chart/indicator-customization/wwwroot/index.html
mdd-updated-custom-indicators
Custom Indicators isn't getting applied. no errors in console.
CustomIndicatorNames is a string[] and should be just a string property
=> mdd-updated-custom-indicators

samples/charts/financial-chart/annotations/Pages/FinancialChartAnnotations.razor, samples/charts/financial-chart/annotations/Services/StocksUtility.cs, samples/charts/financial-chart/axis-types/Services/StocksUtility.cs, samples/charts/financial-chart/high-frequency/Services/StocksUtility.cs, samples/charts/financial-chart/high-volume/Pages/FinancialChartHighVolume.razor, samples/charts/financial-chart/high-volume/Services/StocksUtility.cs, samples/charts/financial-chart/indicator-customization/Pages/FinancialChartCustomIndicators.razor, samples/charts/financial-chart/indicator-customization/Services/StocksUtility.cs, samples/charts/financial-chart/indicator-types/Pages/FinancialChartIndicatorTypes.razor, samples/charts/financial-chart/indicator-types/Services/StocksUtility.cs, samples/charts/financial-chart/overview/Pages/FinancialChartOverview.razor, samples/charts/financial-chart/overview/Services/StockHistory.cs, samples/charts/financial-chart/performance/Services/StocksUtility.cs, samples/charts/financial-chart/volume-types/Services/StocksUtility.cs, samples/charts/pie-chart/explosion/Pages/PieChartExplosion.razor
Fixed StockUtility.cs to include correct Dates on Axis
Fixed PieChart explosion
=> mdd-update

samples/layouts/dock-manager/embedding-frames/BlazorClientApp.csproj, samples/layouts/dock-manager/embedding-frames/BlazorClientApp.sln, samples/layouts/dock-manager/embedding-frames/Program.cs, samples/layouts/dock-manager/embedding-frames/Properties/launchSettings.json, samples/layouts/dock-manager/embedding-frames/README.md, samples/layouts/dock-manager/embedding-frames/_Imports.razor, samples/layouts/dock-manager/embedding-frames/wwwroot/index.css, samples/layouts/dock-manager/embedding-frames/wwwroot/index.html, samples/layouts/dock-manager/overview/App.razor, samples/layouts/dock-manager/overview/BlazorClientApp.csproj, samples/layouts/dock-manager/overview/BlazorClientApp.sln, samples/layouts/dock-manager/overview/Pages/DockManagerOverview.razor, samples/layouts/dock-manager/overview/Program.cs, samples/layouts/dock-manager/overview/Properties/launchSettings.json, samples/layouts/dock-manager/overview/README.md, samples/layouts/dock-manager/overview/Services/DataGenerator.cs, samples/layouts/dock-manager/overview/Services/EmployeeData.cs, samples/layouts/dock-manager/overview/_Imports.razor, samples/layouts/dock-manager/overview/wwwroot/index.css, samples/layouts/dock-manager/overview/wwwroot/index.html, samples/layouts/dock-manager/overview/wwwroot/jsInterop.js, samples/layouts/dock-manager/updating-panes/BlazorClientApp.csproj, samples/layouts/dock-manager/updating-panes/BlazorClientApp.sln, samples/layouts/dock-manager/updating-panes/Program.cs, samples/layouts/dock-manager/updating-panes/Properties/launchSettings.json, samples/layouts/dock-manager/updating-panes/README.md, samples/layouts/dock-manager/updating-panes/_Imports.razor, samples/layouts/dock-manager/updating-panes/wwwroot/index.css, samples/layouts/dock-manager/updating-panes/wwwroot/index.html
=> mdd-checkback-in-dockmanager

samples/maps/geo-map/binding-data-csv/Pages/MapBindingDataCSV.razor, samples/maps/geo-map/type-scatter-density-series/Pages/MapTypeScatterDensitySeries.razor
=> mdd-update-zoom-level

samples/charts/category-chart/annotations/Pages/CategoryChartAnnotations.razor, samples/charts/data-chart/type-polar-spline-area-series/Pages/DataChartTypePolarSplineAreaSeries.razor, samples/charts/financial-chart/annotations/Pages/FinancialChartAnnotations.razor, samples/grids/data-grid/column-chooser-picker/Pages/DataGridColumnChooserPicker.razor, samples/grids/data-grid/column-chooser-toolbar/Pages/DataGridColumnChooserToolbar.razor, samples/grids/data-grid/column-pinning-picker/Pages/DataGridColumnPinningPicker.razor
=> mdd-fixed-samples

samples/grids/data-grid/row-highlighting/App.razor, samples/grids/data-grid/row-highlighting/BlazorClientApp.csproj, samples/grids/data-grid/row-highlighting/BlazorClientApp.sln, samples/grids/data-grid/row-highlighting/Pages/DataGridRowHighlighting.razor, samples/grids/data-grid/row-highlighting/Program.cs, samples/grids/data-grid/row-highlighting/Properties/launchSettings.json, samples/grids/data-grid/row-highlighting/README.md, samples/grids/data-grid/row-highlighting/Services/DataGenerator.cs, samples/grids/data-grid/row-highlighting/Services/EmployeeData.cs, samples/grids/data-grid/row-highlighting/_Imports.razor, samples/grids/data-grid/row-highlighting/wwwroot/index.css, samples/grids/data-grid/row-highlighting/wwwroot/index.html
=> mdd-row-highlighting

samples/grids/data-grid/accessibility/App.razor, samples/grids/data-grid/accessibility/BlazorClientApp.csproj, samples/grids/data-grid/accessibility/BlazorClientApp.sln, samples/grids/data-grid/accessibility/Pages/DataGridAccessibility.razor, samples/grids/data-grid/accessibility/Program.cs, samples/grids/data-grid/accessibility/Properties/launchSettings.json, samples/grids/data-grid/accessibility/README.md, samples/grids/data-grid/accessibility/_Imports.razor, samples/grids/data-grid/accessibility/wwwroot/index.css, samples/grids/data-grid/accessibility/wwwroot/index.html
=> mdd-grid-accessibility

samples/grids/data-grid/binding-live-data/Pages/DataGridBindingLiveData.razor, samples/grids/data-grid/performance/Pages/DataGridPerformance.razor
=> mdd-row-hover-off

samples/grids/data-grid/cell-editing/Pages/DataGridCellEditing.razor
hooked roweditStarted and roweditEnded events instead of using activeCellChanged
=> mdd-added-row-edit-events

.gitignore, browser/IgBlazorSamples.Client/wwwroot/index.html, samples/excel/excel-library/overview/App.razor, samples/excel/excel-library/overview/BlazorClientApp.csproj, samples/excel/excel-library/overview/BlazorClientApp.sln, samples/excel/excel-library/overview/Pages/ExcelLibraryOverview.razor, samples/excel/excel-library/overview/Program.cs, samples/excel/excel-library/overview/Properties/launchSettings.json, samples/excel/excel-library/overview/README.md, samples/excel/excel-library/overview/Services/ExcelUtility.cs, samples/excel/excel-library/overview/_Imports.razor, samples/excel/excel-library/overview/wwwroot/BlazorDownloadFile.js, samples/excel/excel-library/overview/wwwroot/index.css, samples/excel/excel-library/overview/wwwroot/index.html
=> mdd-first-excel-sample

samples/excel/excel-library/operations-on-worksheets/App.razor, samples/excel/excel-library/operations-on-worksheets/BlazorClientApp.csproj, samples/excel/excel-library/operations-on-worksheets/BlazorClientApp.sln, samples/excel/excel-library/operations-on-worksheets/Pages/ExcelLibraryWorksheetOperations.razor, samples/excel/excel-library/operations-on-worksheets/Program.cs, samples/excel/excel-library/operations-on-worksheets/Properties/launchSettings.json, samples/excel/excel-library/operations-on-worksheets/README.md, samples/excel/excel-library/operations-on-worksheets/_Imports.razor, samples/excel/excel-library/operations-on-worksheets/wwwroot/BlazorDownloadFile.js, samples/excel/excel-library/operations-on-worksheets/wwwroot/index.css, samples/excel/excel-library/operations-on-worksheets/wwwroot/index.html
=> mdd-worksheet-operations

samples/excel/excel-library/working-with-cells/App.razor, samples/excel/excel-library/working-with-cells/BlazorClientApp.csproj, samples/excel/excel-library/working-with-cells/BlazorClientApp.sln, samples/excel/excel-library/working-with-cells/Pages/ExcelLibraryWorkingWithCells.razor, samples/excel/excel-library/working-with-cells/Program.cs, samples/excel/excel-library/working-with-cells/Properties/launchSettings.json, samples/excel/excel-library/working-with-cells/README.md, samples/excel/excel-library/working-with-cells/_Imports.razor, samples/excel/excel-library/working-with-cells/wwwroot/BlazorDownloadFile.js, samples/excel/excel-library/working-with-cells/wwwroot/index.css, samples/excel/excel-library/working-with-cells/wwwroot/index.html
=> mdd-working-with-cells

samples/charts/financial-chart/annotations/Pages/FinancialChartAnnotations.razor, samples/grids/data-grid/column-pinning-picker/Pages/DataGridColumnPinningPicker.razor, samples/grids/data-grid/column-pinning-toolbar/Pages/DataGridColumnPinningToolbar.razor
=> mdd-bug-fixing

samples/charts/doughnut-chart/explosion/Pages/DoughnutChartExplosion.razor, samples/charts/doughnut-chart/legend/Pages/DoughnutChartLegend.razor, samples/charts/doughnut-chart/selection/Pages/DoughnutChartSelection.razor
=> Doughnut Chart samples SEO

samples/charts/data-chart/stacked-bar-chart/App.razor, samples/charts/data-chart/stacked-bar-chart/Services/SampleStackedData.cs
Moved the calloutdata class to app razor
=> Moved the calloutData to razor file

samples/charts/data-chart/polar-area-chart-styling/App.razor, samples/charts/data-chart/polar-area-chart-styling/BlazorClientApp.csproj, samples/charts/data-chart/polar-area-chart-styling/BlazorClientApp.sln, samples/charts/data-chart/polar-area-chart-styling/Program.cs, samples/charts/data-chart/polar-area-chart-styling/Properties/launchSettings.json, samples/charts/data-chart/polar-area-chart-styling/README.md, samples/charts/data-chart/polar-area-chart-styling/Services/SamplePolarData.cs, samples/charts/data-chart/polar-area-chart-styling/_Imports.razor, samples/charts/data-chart/polar-area-chart-styling/wwwroot/index.css, samples/charts/data-chart/polar-area-chart-styling/wwwroot/index.html, samples/charts/data-chart/radial-area-chart-styling/App.razor, samples/charts/data-chart/radial-area-chart-styling/BlazorClientApp.csproj, samples/charts/data-chart/radial-area-chart-styling/BlazorClientApp.sln, samples/charts/data-chart/radial-area-chart-styling/Program.cs, samples/charts/data-chart/radial-area-chart-styling/Properties/launchSettings.json, samples/charts/data-chart/radial-area-chart-styling/README.md, samples/charts/data-chart/radial-area-chart-styling/Services/PlayerStatsInfo.cs, samples/charts/data-chart/radial-area-chart-styling/_Imports.razor, samples/charts/data-chart/radial-area-chart-styling/wwwroot/index.css, samples/charts/data-chart/radial-area-chart-styling/wwwroot/index.html
Added
Polar Area Styling
Radial Area Styling
=> mdd-seo-add-polar-radial-area-styling

samples/charts/data-chart/chart-navigation/App.razor, samples/charts/data-chart/chart-navigation/Services/SampleFinancialData.cs
mdd-seo-chart-navigation (only)
using dc with financial series
=> mdd-seo-chart-nav

samples/charts/financial-chart/trendlines/App.razor
mdd-seo-updated-existing-financial-chart-sample
=> mdd-seo-trendlines-chart-features

samples/charts/category-chart/column-chart-with-tooltips/App.razor, samples/charts/category-chart/column-chart-with-tooltips/BlazorClientApp.csproj, samples/charts/category-chart/column-chart-with-tooltips/BlazorClientApp.sln, samples/charts/category-chart/column-chart-with-tooltips/Program.cs, samples/charts/category-chart/column-chart-with-tooltips/Properties/launchSettings.json, samples/charts/category-chart/column-chart-with-tooltips/README.md, samples/charts/category-chart/column-chart-with-tooltips/Services/FilmFranchiseRevenueData.cs, samples/charts/category-chart/column-chart-with-tooltips/_Imports.razor, samples/charts/category-chart/column-chart-with-tooltips/wwwroot/index.css, samples/charts/category-chart/column-chart-with-tooltips/wwwroot/index.html
mdd-seo-chart-features-tooltips
=> mdd-seo-chart-features-tooltips

samples/charts/category-chart/line-chart-with-animations/App.razor, samples/charts/category-chart/line-chart-with-animations/BlazorClientApp.csproj, samples/charts/category-chart/line-chart-with-animations/BlazorClientApp.sln, samples/charts/category-chart/line-chart-with-animations/Program.cs, samples/charts/category-chart/line-chart-with-animations/Properties/launchSettings.json, samples/charts/category-chart/line-chart-with-animations/README.md, samples/charts/category-chart/line-chart-with-animations/Services/EnergyRenewableData.cs, samples/charts/category-chart/line-chart-with-animations/_Imports.razor, samples/charts/category-chart/line-chart-with-animations/wwwroot/index.css, samples/charts/category-chart/line-chart-with-animations/wwwroot/index.html
mdd-seo-animations
added new line chart with transitions enabled
=> mdd-seo-animations

samples/charts/category-chart/column-chart-with-highlighting/App.razor, samples/charts/category-chart/column-chart-with-highlighting/BlazorClientApp.csproj, samples/charts/category-chart/column-chart-with-highlighting/BlazorClientApp.sln, samples/charts/category-chart/column-chart-with-highlighting/Program.cs, samples/charts/category-chart/column-chart-with-highlighting/Properties/launchSettings.json, samples/charts/category-chart/column-chart-with-highlighting/README.md, samples/charts/category-chart/column-chart-with-highlighting/Services/CityTemperatureData.cs, samples/charts/category-chart/column-chart-with-highlighting/_Imports.razor, samples/charts/category-chart/column-chart-with-highlighting/wwwroot/index.css, samples/charts/category-chart/column-chart-with-highlighting/wwwroot/index.html
mdd-seo-chart-features-highlighting
=> mdd-seo-chart-features-highlighting

samples/charts/data-chart/tooltip-template/App.razor, samples/charts/data-chart/tooltip-template/BlazorClientApp.csproj, samples/charts/data-chart/tooltip-template/BlazorClientApp.sln, samples/charts/data-chart/tooltip-template/Program.cs, samples/charts/data-chart/tooltip-template/Properties/launchSettings.json, samples/charts/data-chart/tooltip-template/README.md, samples/charts/data-chart/tooltip-template/Services/EnergyProductionData.cs, samples/charts/data-chart/tooltip-template/_Imports.razor, samples/charts/data-chart/tooltip-template/wwwroot/DataChartTooltipStyles.js, samples/charts/data-chart/tooltip-template/wwwroot/index.css, samples/charts/data-chart/tooltip-template/wwwroot/index.html
=> mdd-seo-tooltip

samples/grids/data-grid/load-save-layout/App.razor, samples/grids/data-grid/load-save-layout/BlazorClientApp.csproj, samples/grids/data-grid/load-save-layout/BlazorClientApp.sln, samples/grids/data-grid/load-save-layout/Program.cs, samples/grids/data-grid/load-save-layout/Properties/launchSettings.json, samples/grids/data-grid/load-save-layout/README.md, samples/grids/data-grid/load-save-layout/Services/DataGenerator.cs, samples/grids/data-grid/load-save-layout/Services/EmployeeData.cs, samples/grids/data-grid/load-save-layout/_Imports.razor, samples/grids/data-grid/load-save-layout/wwwroot/DataGridOverview.js, samples/grids/data-grid/load-save-layout/wwwroot/index.css, samples/grids/data-grid/load-save-layout/wwwroot/index.html
=> mdd-load-save-layout

samples/scheduling/calendar/disabled-dates/App.razor, samples/scheduling/calendar/disabled-dates/BlazorClientApp.csproj, samples/scheduling/calendar/disabled-dates/wwwroot/index.html, samples/scheduling/calendar/formatting/App.razor, samples/scheduling/calendar/formatting/wwwroot/index.html, samples/scheduling/calendar/header/App.razor, samples/scheduling/calendar/header/wwwroot/index.html, samples/scheduling/calendar/multiple-months/App.razor, samples/scheduling/calendar/multiple-months/BlazorClientApp.csproj, samples/scheduling/calendar/multiple-months/wwwroot/index.html, samples/scheduling/calendar/multiple-selection/App.razor, samples/scheduling/calendar/multiple-selection/wwwroot/index.html, samples/scheduling/calendar/overview/App.razor, samples/scheduling/calendar/overview/wwwroot/index.html, samples/scheduling/calendar/range-selection/App.razor, samples/scheduling/calendar/range-selection/wwwroot/index.html, samples/scheduling/calendar/size/App.razor, samples/scheduling/calendar/size/wwwroot/index.html, samples/scheduling/calendar/special-dates/App.razor, samples/scheduling/calendar/special-dates/wwwroot/index.html, samples/scheduling/calendar/styling/App.razor, samples/scheduling/calendar/styling/wwwroot/CalendarStyling.css, samples/scheduling/calendar/styling/wwwroot/index.html, samples/scheduling/calendar/week-numbers/App.razor, samples/scheduling/calendar/week-numbers/wwwroot/index.html
Added IgbCalendar samples
TODO - properties missing etc.
=> mdd-add-calendar

samples/menus/nav-drawer/add-drawer-items/App.razor, samples/menus/nav-drawer/add-drawer-items/wwwroot/index.html, samples/menus/nav-drawer/add-mini/App.razor, samples/menus/nav-drawer/add-mini/wwwroot/index.html, samples/menus/nav-drawer/add-positions-navbar/App.razor, samples/menus/nav-drawer/add-positions-navbar/wwwroot/index.html, samples/menus/nav-drawer/styling/App.razor, samples/menus/nav-drawer/styling/wwwroot/drawer-styling.css, samples/menus/nav-drawer/styling/wwwroot/index.html
=> mdd-IgbNavDrawer

samples/menus/nav-bar/content/App.razor, samples/menus/nav-bar/content/wwwroot/index.html, samples/menus/nav-bar/overview/App.razor, samples/menus/nav-bar/overview/wwwroot/index.html, samples/menus/nav-bar/styling/App.razor, samples/menus/nav-bar/styling/wwwroot/NavbarStyling.css, samples/menus/nav-bar/styling/wwwroot/index.html
=> mdd-Navbar

samples/inputs/form/overview/App.razor, samples/inputs/form/overview/wwwroot/index.html
=> mdd-igb-form

samples/inputs/ripple/button/App.razor, samples/inputs/ripple/button/BlazorClientApp.csproj, samples/inputs/ripple/button/BlazorClientApp.sln, samples/inputs/ripple/button/Program.cs, samples/inputs/ripple/button/Properties/launchSettings.json, samples/inputs/ripple/button/README.md, samples/inputs/ripple/button/_Imports.razor, samples/inputs/ripple/button/wwwroot/index.css, samples/inputs/ripple/button/wwwroot/index.html, samples/inputs/ripple/color/App.razor, samples/inputs/ripple/color/BlazorClientApp.csproj, samples/inputs/ripple/color/BlazorClientApp.sln, samples/inputs/ripple/color/Program.cs, samples/inputs/ripple/color/Properties/launchSettings.json, samples/inputs/ripple/color/README.md, samples/inputs/ripple/color/_Imports.razor, samples/inputs/ripple/color/wwwroot/index.css, samples/inputs/ripple/color/wwwroot/index.html
=> mdd-igb-ripple

samples/inputs/radio/alignment/App.razor, samples/inputs/radio/alignment/wwwroot/index.html, samples/inputs/radio/disabled/App.razor, samples/inputs/radio/disabled/wwwroot/index.html, samples/inputs/radio/group/App.razor, samples/inputs/radio/group/wwwroot/index.html, samples/inputs/radio/invalid/App.razor, samples/inputs/radio/invalid/wwwroot/index.html, samples/inputs/radio/label/App.razor, samples/inputs/radio/label/wwwroot/index.html, samples/inputs/radio/styling/App.razor, samples/inputs/radio/styling/wwwroot/index.css, samples/inputs/radio/styling/wwwroot/index.html
=> mdd-igb-radio

samples/editors/date-picker/format/App.razor
=> increase size of datepicker

samples/grids/data-grid/cell-merging/App.razor, samples/grids/data-grid/row-group-descriptions/App.razor, samples/grids/data-grid/row-group-descriptions/BlazorClientApp.csproj, samples/grids/data-grid/row-group-descriptions/BlazorClientApp.sln, samples/grids/data-grid/row-group-descriptions/Program.cs, samples/grids/data-grid/row-group-descriptions/Properties/launchSettings.json, samples/grids/data-grid/row-group-descriptions/README.md, samples/grids/data-grid/row-group-descriptions/Services/DataGenerator.cs, samples/grids/data-grid/row-group-descriptions/Services/EmployeeData.cs, samples/grids/data-grid/row-group-descriptions/_Imports.razor, samples/grids/data-grid/row-group-descriptions/wwwroot/index.css, samples/grids/data-grid/row-group-descriptions/wwwroot/index.html, samples/grids/data-grid/row-grouping/BlazorClientApp.csproj
mdd-update-row-grouping-samples
brian's feedback
=> mdd-update-row-grouping-samples

samples/grids/data-grid/row-group-descriptions/App.razor
replace country flag to country
=> Update Country Field 

samples/charts/financial-chart/axis-scale/App.razor, samples/charts/financial-chart/axis-scale/BlazorClientApp.csproj, samples/charts/financial-chart/axis-scale/BlazorClientApp.sln, samples/charts/financial-chart/axis-scale/Program.cs, samples/charts/financial-chart/axis-scale/Properties/launchSettings.json, samples/charts/financial-chart/axis-scale/README.md, samples/charts/financial-chart/axis-scale/Services/StocksUtility.cs, samples/charts/financial-chart/axis-scale/_Imports.razor, samples/charts/financial-chart/axis-scale/wwwroot/index.css, samples/charts/financial-chart/axis-scale/wwwroot/index.html
Added sample for
https://github.com/IgniteUI/igniteui-xplat-docs/pull/289/
=> mdd-axis-mode-&-scale

samples/inputs/input/binding/App.razor, samples/inputs/input/binding/BlazorClientApp.csproj, samples/inputs/input/binding/BlazorClientApp.sln, samples/inputs/input/binding/Program.cs, samples/inputs/input/binding/Properties/launchSettings.json, samples/inputs/input/binding/README.md, samples/inputs/input/binding/_Imports.razor, samples/inputs/input/binding/wwwroot/index.css, samples/inputs/input/binding/wwwroot/index.html
=> mdd-IgbInput Binding

samples/excel/excel-library/operations-on-worksheets/App.razor, samples/grids/data-grid/cell-activation/App.razor
=> Bug Fixing

samples/scheduling/calendar/week-numbers/App.razor
=> mdd-273924

samples/charts/category-chart/axis-gap/App.razor
Added min and max gap to axis-gap sample
=> mdd-min-max-gap

samples/grids/data-grid/localization/App.razor, samples/grids/data-grid/localization/Services/EmployeeDataJA.cs
update ja version of Employee Data
=> update ja version of Employee Data

samples/grids/tree/basic-example/App.razor, samples/grids/tree/basic-example/BlazorClientApp.csproj, samples/grids/tree/basic-example/BlazorClientApp.sln, samples/grids/tree/basic-example/Program.cs, samples/grids/tree/basic-example/Properties/launchSettings.json, samples/grids/tree/basic-example/README.md, samples/grids/tree/basic-example/_Imports.razor, samples/grids/tree/basic-example/wwwroot/index.css, samples/grids/tree/basic-example/wwwroot/index.html
=> mdd-basic-tree-sample

samples/charts/category-chart/high-frequency/App.razor
=> Remove default markers

samples/charts/category-chart/high-volume/App.razor
=> Improve High-Volume

samples/grids/grid/search-sample/App.razor, samples/grids/grid/search-sample/BlazorClientApp.csproj, samples/grids/grid/search-sample/BlazorClientApp.sln, samples/grids/grid/search-sample/Program.cs, samples/grids/grid/search-sample/Properties/launchSettings.json, samples/grids/grid/search-sample/README.md, samples/grids/grid/search-sample/Services/MarketData.cs, samples/grids/grid/search-sample/_Imports.razor, samples/grids/grid/search-sample/wwwroot/index.css, samples/grids/grid/search-sample/wwwroot/index.html
Adding search sample related to porting topic https://github.com/IgniteUI/igniteui-docfx/blob/master/en/components/grids_templates/search.md
=> Add Grid Search Sample.

samples/grids/grid/multi-cell-selection-mode/App.razor, samples/grids/grid/multi-cell-selection-mode/wwwroot/GridRangeSelectedScript.js, samples/grids/grid/multi-cell-selection-mode/wwwroot/index.html
getSelectedData works in JS only.
=> mdd-fix-multi-cell-selection-mode-in-JS

samples/grids/tree-grid/overview/App.razor, samples/grids/tree-grid/overview/BlazorClientApp.csproj, samples/grids/tree-grid/overview/BlazorClientApp.sln, samples/grids/tree-grid/overview/EmployeesNestedData.cs, samples/grids/tree-grid/overview/Program.cs, samples/grids/tree-grid/overview/Properties/launchSettings.json, samples/grids/tree-grid/overview/_Imports.razor, samples/grids/tree-grid/overview/wwwroot/index.css, samples/grids/tree-grid/overview/wwwroot/index.html
mdd-tree-grid-overview
updated to v622
=> mdd-tree-grid-overview

samples/charts/category-chart/data-aggregations/App.razor, samples/charts/category-chart/data-aggregations/BlazorClientApp.csproj, samples/charts/category-chart/data-aggregations/BlazorClientApp.sln, samples/charts/category-chart/data-aggregations/Program.cs, samples/charts/category-chart/data-aggregations/Properties/launchSettings.json, samples/charts/category-chart/data-aggregations/Services/AggregateSalesData.cs, samples/charts/category-chart/data-aggregations/Services/SalesData.cs, samples/charts/category-chart/data-aggregations/_Imports.razor, samples/charts/category-chart/data-aggregations/wwwroot/index.css, samples/charts/category-chart/data-aggregations/wwwroot/index.html, samples/grids/grid/multi-column-headers-export/App.razor
=> mdd-add-chart-aggregations

samples/inputs/input/binding/App.razor
Remove displaytype - Input binding sample
=> Remove displaytype - Input binding sample

samples/grids/grid/data-batch-editing-actions/App.razor, samples/grids/grid/data-paste-options/App.razor, samples/grids/grid/data-validator-service-cross-field/App.razor, samples/grids/grid/data-validator-service-extended/App.razor, samples/grids/grid/data-validator-service/App.razor, samples/grids/grid/multi-row-layout-options/App.razor
https://github.com/IgniteUI/igniteui-xplat-docs/issues/624
=> mdd-remove-batch-editing

samples/maps/geo-map/display-esri-imagery/Properties/launchSettings.json, samples/maps/geo-map/display-esri-imagery/Services/EsriUtility.cs
=> mdd-update-ocean-url-ESRI

samples/grids/grid/data-searching/App.razor, samples/grids/grid/row-selection-mode/App.razor
=> mdd-updates

samples/inputs/linear-progress-indicator/dynamic/App.razor
=> Set non-zero default value to the IgbLinearProgress

browser/IgBlazorSamples.Client/wwwroot/index.html, browser/IgBlazorSamples.Core/Navigation/BrowserLayout.razor
=> Add a way to prevent document scroll in the samples browser

azure-pipelines/build-pipeline-client.yml, azure-pipelines/templates/build-steps-template.yml
Also opened a bug to MS about this: https://github.com/microsoft/azure-pipelines-tasks/issues/19171
I hope they fix it soon & we get to use both VMs as before & the latest build of dotnet 6
=> Use agent that works with dotnet 6.0.415

browser/IgBlazorSamples.Core/Navigation/BrowserLayout.razor, samples/grids/tree-grid/multi-column-headers-overview/App.razor
made ValueTask projects > public
=> mdd-fix-browserlayout

samples/charts/toolbar/custom-tool/App.razor, samples/charts/toolbar/custom-tool/BlazorClientApp.csproj, samples/charts/toolbar/custom-tool/BlazorClientApp.sln, samples/charts/toolbar/custom-tool/CountryRenewableElectricity.cs, samples/charts/toolbar/custom-tool/Program.cs, samples/charts/toolbar/custom-tool/Properties/launchSettings.json, samples/charts/toolbar/custom-tool/ReadMe.md, samples/charts/toolbar/custom-tool/_Imports.razor, samples/charts/toolbar/custom-tool/wwwroot/index.css, samples/charts/toolbar/custom-tool/wwwroot/index.html
=> mdd-add-custom-tool

samples/grids/grid/state-persistence-about/App.razor, samples/grids/grid/state-persistence-about/BlazorClientApp.csproj, samples/grids/grid/state-persistence-about/BlazorClientApp.sln, samples/grids/grid/state-persistence-about/Program.cs, samples/grids/grid/state-persistence-about/Properties/launchSettings.json, samples/grids/grid/state-persistence-about/ReadMe.md, samples/grids/grid/state-persistence-about/_Imports.razor, samples/grids/grid/state-persistence-about/wwwroot/index.css, samples/grids/grid/state-persistence-about/wwwroot/index.html, samples/grids/grid/state-persistence-main/App.razor, samples/grids/grid/state-persistence-main/BlazorClientApp.csproj, samples/grids/grid/state-persistence-main/BlazorClientApp.sln, samples/grids/grid/state-persistence-main/CustomersData.cs, samples/grids/grid/state-persistence-main/Program.cs, samples/grids/grid/state-persistence-main/Properties/launchSettings.json, samples/grids/grid/state-persistence-main/ReadMe.md, samples/grids/grid/state-persistence-main/_Imports.razor, samples/grids/grid/state-persistence-main/wwwroot/index.css, samples/grids/grid/state-persistence-main/wwwroot/index.html
Related https://github.com/IgniteUI/igniteui-xplat-examples/issues/410
=> Add custom state persistence sample pages.

samples/grids/grid/clipboard-operations/App.razor, samples/grids/grid/clipboard-operations/Program.cs, samples/grids/grid/clipboard-operations/wwwroot/events.js
Update UI elements since the property editor ones do not work correctly.
=> Update clipboard operations sample.

samples/grids/grid/state-persistence-main/App.razor
Add missed IgbGridToolbarActions component around the toolbar actions so that they render in the sample.
=> Minor fix for the states sample.

samples/charts/toolbar/download-data-chart-as-image/App.razor, samples/charts/toolbar/download-data-chart-as-image/BlazorClientApp.csproj, samples/charts/toolbar/download-data-chart-as-image/BlazorClientApp.sln, samples/charts/toolbar/download-data-chart-as-image/CountryRenewableElectricity.cs, samples/charts/toolbar/download-data-chart-as-image/Program.cs, samples/charts/toolbar/download-data-chart-as-image/Properties/launchSettings.json, samples/charts/toolbar/download-data-chart-as-image/ReadMe.md, samples/charts/toolbar/download-data-chart-as-image/_Imports.razor, samples/charts/toolbar/download-data-chart-as-image/wwwroot/ImageRender.js, samples/charts/toolbar/download-data-chart-as-image/wwwroot/index.css, samples/charts/toolbar/download-data-chart-as-image/wwwroot/index.html
=> mdd-download-chart-as-image

browser/IgBlazorSamples.Core/Navigation/BrowserLayout.razor
=> Add a check to disable prevent scroll logic for blazor server

samples/grids/list/overview/App.razor, samples/inputs/button/size/App.razor, samples/inputs/input/size/App.razor, samples/inputs/radio/alignment/App.razor, samples/inputs/radio/disabled/App.razor, samples/inputs/radio/group/App.razor, samples/inputs/radio/label/App.razor, samples/inputs/radio/styling/App.razor, samples/layouts/accordion/customization/App.razor, samples/layouts/stepper/linear/App.razor, samples/layouts/stepper/orientation/App.razor, samples/layouts/stepper/overview/App.razor, samples/layouts/stepper/steptypes/App.razor, samples/layouts/tabs/alignment/App.razor, samples/menus/nav-drawer/add-positions-navbar/App.razor, samples/scheduling/calendar/formatting/App.razor, samples/scheduling/calendar/size/App.razor
=> fix(radio): add name attribute to all radio buttons

samples/menus/nav-drawer/add-drawer-items/App.razor, samples/menus/nav-drawer/add-mini/App.razor, samples/menus/nav-drawer/add-positions-navbar/App.razor, samples/menus/nav-drawer/styling/App.razor
=> fix(nav-drawer): refactor samples

samples/gauges/radial-gauge/optical-scaling/App.razor, samples/gauges/radial-gauge/optical-scaling/BlazorClientApp.csproj, samples/gauges/radial-gauge/optical-scaling/BlazorClientApp.sln, samples/gauges/radial-gauge/optical-scaling/Program.cs, samples/gauges/radial-gauge/optical-scaling/Properties/launchSettings.json, samples/gauges/radial-gauge/optical-scaling/README.md, samples/gauges/radial-gauge/optical-scaling/Services/GaugeRangeInfo.cs, samples/gauges/radial-gauge/optical-scaling/_Imports.razor, samples/gauges/radial-gauge/optical-scaling/wwwroot/index.css, samples/gauges/radial-gauge/optical-scaling/wwwroot/index.html
=> mdd-optical-scaling

samples/gauges/radial-gauge/optical-scaling/App.razor
mdd-tweak-inputs-optical-scaling
=> mdd-tweak-inputs-optical-scaling

samples/charts/category-chart/format-specifiers/App.razor
mdd-fix-format-specifiers
Keep this until we resolve code gen export issue
https://infragistics.visualstudio.com/NetAdvantage/_workitems/edit/27052
=> mdd-fix-format-specifiers

samples/gauges/bullet-graph/highlight-needle/App.razor, samples/gauges/bullet-graph/highlight-needle/BlazorClientApp.csproj, samples/gauges/bullet-graph/highlight-needle/BlazorClientApp.sln, samples/gauges/bullet-graph/highlight-needle/Program.cs, samples/gauges/bullet-graph/highlight-needle/Properties/launchSettings.json, samples/gauges/bullet-graph/highlight-needle/README.md, samples/gauges/bullet-graph/highlight-needle/_Imports.razor, samples/gauges/bullet-graph/highlight-needle/wwwroot/index.css, samples/gauges/bullet-graph/highlight-needle/wwwroot/index.html, samples/gauges/linear-gauge/highlight-needle/App.razor, samples/gauges/linear-gauge/highlight-needle/BlazorClientApp.csproj, samples/gauges/linear-gauge/highlight-needle/BlazorClientApp.sln, samples/gauges/linear-gauge/highlight-needle/Program.cs, samples/gauges/linear-gauge/highlight-needle/Properties/launchSettings.json, samples/gauges/linear-gauge/highlight-needle/README.md, samples/gauges/linear-gauge/highlight-needle/_Imports.razor, samples/gauges/linear-gauge/highlight-needle/wwwroot/index.css, samples/gauges/linear-gauge/highlight-needle/wwwroot/index.html, samples/gauges/radial-gauge/highlight-needle/App.razor, samples/gauges/radial-gauge/highlight-needle/BlazorClientApp.csproj, samples/gauges/radial-gauge/highlight-needle/BlazorClientApp.sln, samples/gauges/radial-gauge/highlight-needle/Program.cs, samples/gauges/radial-gauge/highlight-needle/Properties/launchSettings.json, samples/gauges/radial-gauge/highlight-needle/README.md, samples/gauges/radial-gauge/highlight-needle/Services/GaugeRangeInfo.cs, samples/gauges/radial-gauge/highlight-needle/_Imports.razor, samples/gauges/radial-gauge/highlight-needle/wwwroot/index.css, samples/gauges/radial-gauge/highlight-needle/wwwroot/index.html
=> mdd-highlight-needle-gauges

samples/grids/grid/infinite-scroll/App.razor
https://services.odata.org/northwind/northwind.svc/Products
=> update northwind service

samples/charts/tree-map/highlighting-percent-based/App.razor, samples/charts/tree-map/highlighting-percent-based/BlazorClientApp.csproj, samples/charts/tree-map/highlighting-percent-based/BlazorClientApp.sln, samples/charts/tree-map/highlighting-percent-based/CountryTopUrbanPopData.cs, samples/charts/tree-map/highlighting-percent-based/Program.cs, samples/charts/tree-map/highlighting-percent-based/Properties/launchSettings.json, samples/charts/tree-map/highlighting-percent-based/README.md, samples/charts/tree-map/highlighting-percent-based/_Imports.razor, samples/charts/tree-map/highlighting-percent-based/wwwroot/index.css, samples/charts/tree-map/highlighting-percent-based/wwwroot/index.html
mdd-tree-map-percent-based-highlighting
=> mdd-tree-map-percent-based-highlighting

azure-pipelines/build-pipeline-client.yml, azure-pipelines/build-pipeline-server.yml, templates/BlazorClientApp/BlazorClientApp.csproj, templates/sample/BlazorClientApp.csproj
=> mdd-update-218-misc

samples/grids/tree-grid/column-data-types/App.razor, samples/grids/tree-grid/column-data-types/BlazorClientApp.csproj, samples/grids/tree-grid/column-data-types/BlazorClientApp.sln, samples/grids/tree-grid/column-data-types/EmployeesData.cs, samples/grids/tree-grid/column-data-types/Program.cs, samples/grids/tree-grid/column-data-types/Properties/launchSettings.json, samples/grids/tree-grid/column-data-types/_Imports.razor, samples/grids/tree-grid/column-data-types/wwwroot/index.css, samples/grids/tree-grid/column-data-types/wwwroot/index.html
Related to https://github.com/IgniteUI/igniteui-xplat-docs/issues/748
=> Add Tree Grid column types sample

samples/inputs/date-time-input/input-format-display-format/App.razor, samples/inputs/date-time-input/min-max-value/App.razor, samples/inputs/date-time-input/overview/App.razor
Closes [#1057](https://github.com/IgniteUI/igniteui-xplat-docs/issues/1057)
=> DateTimeInput samples add up/down buttons

samples/layouts/stepper/linear/wwwroot/index.css, samples/layouts/stepper/linear/wwwroot/index.html
=> fix(stepper-overview): add margins to switch and button

azure-pipelines/build-pipeline-client.yml, azure-pipelines/build-pipeline-server.yml, azure-pipelines/templates/build-steps-template.yml
https://infragistics.visualstudio.com/NetAdvantage/_build/results?buildId=154066&view=results
=> revert PR #677 due to build error

samples/grids/tree-grid/multi-cell-selection-mode/App.razor, samples/grids/tree-grid/multi-cell-selection-mode/BlazorClientApp.csproj, samples/grids/tree-grid/multi-cell-selection-mode/BlazorClientApp.sln, samples/grids/tree-grid/multi-cell-selection-mode/EmployeesFlatData.cs, samples/grids/tree-grid/multi-cell-selection-mode/Program.cs, samples/grids/tree-grid/multi-cell-selection-mode/Properties/launchSettings.json, samples/grids/tree-grid/multi-cell-selection-mode/ReadMe.md, samples/grids/tree-grid/multi-cell-selection-mode/_Imports.razor, samples/grids/tree-grid/multi-cell-selection-mode/wwwroot/events.js, samples/grids/tree-grid/multi-cell-selection-mode/wwwroot/index.css, samples/grids/tree-grid/multi-cell-selection-mode/wwwroot/index.html
Closes #[648](https://github.com/IgniteUI/igniteui-xplat-examples/issues/648)
=> Add tree grid multi cell selection mode sample for Blazor

samples/grids/pivot-grid/data-selector/App.razor
This sample is not generated from: https://github.com/IgniteUI/igniteui-xplat-examples/tree/23.2.x/samples/grids/pivot-grid
So updating the types manually.
=> Update custom pivot sample with new array types.

samples/grids/grid/data-searching/App.razor
Closes: [632](https://github.com/IgniteUI/igniteui-xplat-examples/issues/632)
=> Adding search grid consistency accross all platforms

samples/grids/grid/multi-row-dragging/App.razor, samples/grids/grid/multi-row-dragging/wwwroot/GridRowDragToGridEvents.js, samples/grids/grid/row-drag-base/wwwroot/GridRowDragBaseEvents.js, samples/grids/grid/row-drag-to-grid/wwwroot/GridRowDragToGridEvents.js, samples/grids/hierarchical-grid/row-drag-base/App.razor, samples/grids/hierarchical-grid/row-drag-base/wwwroot/GridRowDragBaseEvents.js, samples/grids/tree-grid/multi-cell-selection-mode/App.razor, samples/grids/tree-grid/multi-cell-selection-mode/wwwroot/events.js, samples/grids/tree-grid/row-drag-base/App.razor, samples/grids/tree-grid/row-drag-base/wwwroot/GridRowDragBase.js
Related to: https://github.com/IgniteUI/igniteui-xplat-examples/issues/703
=> chore(*): Adjust method names to prevent collisions.

samples/grids/grid/change-icons-custom/App.razor, samples/grids/grid/change-icons-custom/BlazorClientApp.csproj, samples/grids/grid/change-icons-custom/BlazorClientApp.sln, samples/grids/grid/change-icons-custom/NwindData.cs, samples/grids/grid/change-icons-custom/Program.cs, samples/grids/grid/change-icons-custom/Properties/launchSettings.json, samples/grids/grid/change-icons-custom/ReadMe.md, samples/grids/grid/change-icons-custom/_Imports.razor, samples/grids/grid/change-icons-custom/wwwroot/index.css, samples/grids/grid/change-icons-custom/wwwroot/index.html
Depends on [this](https://infragistics.visualstudio.com/NetAdvantage/_git/dev-tools/pullrequest/13612) PR.
Needs a newer blazor version that includes the changes.
=> Add change icons in grid blazor sample.

samples/grids/grid/data-searching/App.razor
Resolves https://github.com/IgniteUI/igniteui-xplat-examples/issues/548
=> Fix Grid Data Searching typo

samples/grids/grid/clipboard-operations/App.razor, samples/grids/grid/clipboard-operations/wwwroot/events.js, samples/grids/tree-grid/clipboard-operations/App.razor, samples/grids/tree-grid/clipboard-operations/wwwroot/events.js, samples/layouts/avatar/size/App.razor
Related to https://github.com/IgniteUI/igniteui-xplat-examples/issues/705
=> Add default separator to the clipboard operations samples.

browser/IgBlazorSamples.Client/wwwroot/index.html
closes https://github.com/IgniteUI/igniteui-angular/issues/14716
=> fix(grid): fixed scrolling of grid overlay container

samples/grids/grid/state-persistence-main/App.razor
https://staging.infragistics.com/blazor-client/grids/grid/state-persistence-main Company column is missing data.
=> Fix grid state sample column field

samples/grids/pivot-grid/data-selector/App.razor, samples/grids/pivot-grid/data-selector/PivotSalesData.cs
=> Fix Pivot sample data and data selector grid ref.

browser/IgBlazorSamples.Server/IgBlazorSamples.Server.csproj
fix build add AllowUnsafeBlocks
=> fix build add AllowUnsafeBlocks

samples/grids/grid/toolbar-sample-4/App.razor, samples/grids/grid/toolbar-sample-4/Program.cs, samples/grids/grid/toolbar-sample-4/wwwroot/events.js, samples/grids/grid/toolbar-sample-4/wwwroot/index.html
mdd-add-custom-content-grid-toolbar
=> mdd-add-custom-content-grid-toolbar

samples/grids/pivot-grid/data-selector/PivotSalesData.cs
Related to https://github.com/IgniteUI/igniteui-xplat-examples/pull/754
=> Unify pivot sales data with generated one.

samples/inputs/input/helper-text/App.razor, samples/inputs/input/prefix-suffix/App.razor, samples/inputs/input/styling/App.razor
=> Fix input samples SVGs throwing errors.

samples/inputs/dropdown/position/App.razor
fixed dropdown position sample
#845
=> fixing dropdown position sample

samples/charts/doughnut-chart/explosion/App.razor, samples/charts/doughnut-chart/explosion/wwwroot/events.js, samples/charts/doughnut-chart/explosion/wwwroot/index.html
mdd-fix-doughnut-explosion
azure
35973
=> mdd-fix-doughnut-explosion-35973

browser/IgBlazorSamples.Client/wwwroot/index.html, browser/IgBlazorSamples.Gulp/tasks/gulp-samples.js
mdd-update-module-requirements
=> mdd-update-module-requirements

samples/charts/data-chart/format-specifiers/App.razor, samples/charts/data-chart/format-specifiers/BlazorClientApp.csproj
mdd-add-update-format-specifiers
=> mdd-add-update-format-specifiers
